### ISSUE TITLE
Fix isvariable function

### ISSUE THREAD

**Issue by jaapdejong15** [Herb-AI/HerbGrammar.jl#21]
The `isvariable` function doesn't take into account that symbols might have a corresponding definition in the `Main` or `Base` module or any other module that a user passes to the SymbolTable when evaluating.
Therefore, `isvariable` should take an optional module and also check whether a symbol is defined in either of these three modules before determining something is a variable.

**Comment by IssaHanou** [comment]
Solved by #45
