### ISSUE TITLE
Rename the repo to Grammars.jl to be in line with the Julia module naming.

### ISSUE THREAD

**Issue by THinnerichs** [Herb-AI/HerbGrammar.jl#8]
Submodule is imported by the name of `Grammars`, but the repo is called `Grammar`. Renaming will break a lot of test, examples, etc.

**Comment by jaapdejong15** [comment]
Places where the repo name is used to my knowledge:

- Herb.jl/test/herb_test.jl
- Herb.jl/src/Herb.jl
- Herb.jl/.gitmodules
